query GetTransactions {
  transactions {
    id
    amount
    credit
    debit
    description
    user {
      id
      firstName
      lastName
      dob
    }
    merchant {
      id
      name
      description
    }
  }
}
